"""Schemas for verifier issues (handoff §2.3)."""
from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class IssueType(str, Enum):
    FACTUAL_ERROR = "factual_error"
    MISSING_INFO = "missing_info"
    INCONSISTENCY = "inconsistency"
    UNSUPPORTED_CLAIM = "unsupported_claim"
    AMBIGUITY = "ambiguity"


class Issue(BaseModel):
    id: str = Field(pattern=r"^I\d+$")
    type: IssueType
    description: str
    affected_summaries: list[str] = Field(
        default_factory=list,
        description="Agent IDs of summaries this issue concerns.",
    )
    affected_field: str = Field(
        description=(
            "JSONPath-like locator into the summary, e.g. "
            "'key_contributions[2]' or 'method.overview'."
        )
    )
    claim_text: str
    suggested_paragraphs: list[str] = Field(
        default_factory=list,
        description="Optional paragraph IDs the verifier suspects are relevant.",
    )
    raised_by: list[str] = Field(
        default_factory=list,
        description=(
            "Reviewer agent IDs that flagged this issue. Populated by the "
            "orchestrator in mutual_peer_review mode (one entry = unique "
            "reviewer perspective; multiple entries = consensus). Empty in "
            "single_judge mode. NOT generated by the LLM — set in code "
            "after aggregation."
        ),
    )


class IssueList(BaseModel):
    """Wrapper used as the verifier's structured output (top-level must be object)."""

    issues: list[Issue] = Field(default_factory=list)
